# run configuration options
run:
  timeout: 10m
  issues-exit-code: 2
  tests: true
  modules-download-mode: mod
  allow-parallel-runners: false
  go: '1.20'

# output configuration options
output:
  format: colored-tab
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  path-prefix: ""
  sort-results: true

# linter configuration options
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - deadcode
    - depguard
    - gochecknoglobals
    - gochecknoinits
    - golint
    - ifshort
    - interfacer
    - maligned
    - nlreturn
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    - wsl
  fast: false

# linter configuration options
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false